### ISSUE TITLE
Speed up video generation with static files

### ISSUE THREAD

**Issue by nbeloglazov** [vaukalak/books-video-generator#8]
Video generation is pretty slow right now and it takes hours and sometimes days to generate video. There are some suggestions on how to improve it:

https://stackoverflow.com/questions/32231715/ffmpeg-one-image-video-convert-faster

Another proposal is to create a short video (1s) and then loop it:

https://superuser.com/questions/1417579/speed-up-ffmpeg-still-image-to-video-or-other-software

**Comment by nbeloglazov** [comment]
Concrete example of how to use second approach (looping video).

1. Create 1s video:
    `ffmpeg -loop 1 -framerate 24 -i /tmp/mystery_book.png -pix_fmt yuv420p -c:v libx264 -preset veryfast -t 1 1s.mp4`
2. Concatenate all audio files:
    `ffmpeg -i "concat:001.mp3|002.mp3|003.mp3|004.mp3|..." -ar 48000 -b:a 256k -codec:a libmp3lame result.mp3`
3. Create video of same length as result.mp3 (8455 is length in sec of mp3 file):
    `ffmpeg -stream_loop 8455 -i 1s.mp4 -c copy full_length.mp4`
4. Add audio to the video file:
    `ffmpeg -i full_length.mp4 -i result.mp3 -c copy -map 0:v:0 -map 1:a:0 result.mp4`

**Comment by vaukalak** [comment]
@nbeloglazov yeah, but how to deal with texts overlays in this case?

**Comment by nbeloglazov** [comment]
You are right. For text overlays we'll need to generate separate 1s video for each chapter and then loop them to the full chapter length, add audio and then concatenate each chapter.

It might be harder to implement for non-static backgrounds (when you use a looped mp4 file). But I would optimize for static images first. For us it's the most important use case.
